# This is workflow for Frontend Web App
name: Frontend Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow pull request events but only for the "main" branch
  # pull_request:
  #   branches: ["main"]
  #   paths:
  #     - jarvis-web-app/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: read-all

env:
  AZURE_WEBAPP_NAME: project-jarvis-dev-web-app # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: "./jarvis-web-app/build" # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: "20.x" # set this to the node version to use

jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Codebase
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: "npm install, build & test"
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
        working-directory: ./jarvis-web-app

      - name: "Deploy to Azure WebApp"
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
