# This is CI workflow for Infrastructure
name: CI Infra

# Controls when the workflow will run
on:
  # Triggers the workflow pull request events but only for the "main" branch
  pull_request:
    branches: ["main"]
    paths:
      - jarvis-infra/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# permissions: read-all

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Codebase
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Run Github Super Linter
        uses: super-linter/super-linter@v6.6.0
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: ${{ github.event.pull_request.base.ref }}
          # infra related flags
          VALIDATE_TERRAFORM_FMT: true
          VALIDATE_TERRAFORM_TFLINT: true
          VALIDATE_CHECKOV: true

      # Terraform Init Phase
      - name: Terraform Init Phase
        run: echo "running terraform init .."

      # Terraform Plan Phase
      - name: Terraform Plan Phase
        run: echo "running terraform plan .."
